version: "1.0"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:var/lib/postgresql/data
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=order-app
